### ISSUE TITLE
Sprockets::FileNotFound in Apidoco::Apis#show

### ISSUE THREAD

**Issue by totoblabla3** [72pulses/apidoco#123]
couldn't find file 'angular/1.8.0/angular' with type 'application/javascript'

// about supported directives.
//
//= require angular/1.8.0/angular  < ------- error
//
//= require apidoco/jquery.min
//= require apidoco/jquery.json-viewer

**Comment by totoblabla3** [comment]
I added vendor/assets/apidoco/angular/1.8.0/angular.js in my project
It worked

**Comment by alameenkhader** [comment]
@totoblabla3 Thanks for reporting.
