### ISSUE TITLE
Not loaded assets 

### ISSUE THREAD

**Issue by mhi20** [72pulses/apidoco#35]
This is error in console browser : 

GET http://localhost:3000/stylesheets/apidoco/application.css net::ERR_ABORTED
GET http://localhost:3000/javascripts/apidoco/application.js net::ERR_ABORTED

**Comment by ahsandar** [comment]
temporary fix is copy the `css` and `js` file from the demo app and it works
 https://apidoco-demo.herokuapp.com/docs/apis/v1

**Comment by alameenkhader** [comment]
@mhi20 Set `config.public_file_server.enabled` to true. See https://guides.rubyonrails.org/configuring.html#rails-general-configuration
