### ISSUE TITLE
Alphabetical Ordering Of Endpoints

### ISSUE THREAD

**Issue by dalezak** [72pulses/apidoco#37]
The endpoints are out of order, currently not being sorted alphabetically.

![endpoints](https://user-images.githubusercontent.com/91811/48500027-775c1400-e7ff-11e8-8787-5ab3f34a08a5.png)

Is there an option to specify the ordering of endpoints?

**Comment by MyExperiments** [comment]
@dalezak Please check the documentation. There is a key named sort_order to order the endpoints.

**Comment by dalezak** [comment]
@alfie-max looks like your [PR](https://github.com/72pulses/apidoco/pull/47) would fix the issue, is it possible to merge this @MyExperiments?

Note, the `sort_order` works fine for ordering `index`, `show`, `create`, etc but the models are out of order. if you look at my screenshot above, you'll notice that `Areas` is below `Organizations` and `Tasks`.

**Comment by alfie-max** [comment]
Exactly.. i have 3 level directory structure.
Without the sort, Products comes first for me

![screenshot 2018-12-11 at 2 10 26 am](https://user-images.githubusercontent.com/8247590/49760263-00c11200-fcea-11e8-93b3-5420ddcc03a6.png)

**Comment by alfie-max** [comment]
@MyExperiments any plans to address this issue?
