### ISSUE TITLE
Change The Page Title

### ISSUE THREAD

**Issue by dalezak** [72pulses/apidoco#38]
The page title is currently hardcoded as `Apidoco`, it would be nice to override via a setting.

```
<head>
  <title>Apidoco</title>
  <%= stylesheet_link_tag "apidoco/application", media: "all" %>
  <%= javascript_include_tag "apidoco/application" %>
  <%= csrf_meta_tags %>
</head>
```
https://github.com/72pulses/apidoco/blob/master/app/views/layouts/apidoco/application.html.erb

**Comment by MyExperiments** [comment]
@dalezak Thanks for your suggestion.

Please upgrade the gem to the latest version. You can configure it as mentioned in the Readme.

Thanks,
Sufinsha
