### ISSUE TITLE
[Question] Does this gem works on "api-only" mode?

### ISSUE THREAD

**Issue by danfaiole** [72pulses/apidoco#68]
I tried using the gem in and old project that uses the api only mode in rails but when I access the /docs route it shows just the HTML with angular tags. So... Does the gem work with this type of API?

![image](https://user-images.githubusercontent.com/12055746/77957407-d06c0100-72a9-11ea-8a0a-991a56099e7b.png)
It shows like this in my localhost

The project configs are:
- ruby: 2.4.9
- Rails: 4.2.3

Thanks for the attention!

**Comment by alameenkhader** [comment]
@danfaiole This will not work in api only mode as of now. Thanks for posting the question. In the meantime we will check if there is any way we can make it work with api only mode.
