### ISSUE TITLE
Specifying the "direction" of the parameter.

### ISSUE THREAD

**Issue by danilvoe** [72pulses/apidoco#87]
I'd like to specify in the parameters for a request, or for a response to a request.

for example, to inform that the parameter is optional or to describe it.

In examples of requests, the essence of one or another parameter (in response to a request) may not always be clear.

**Comment by alameenkhader** [comment]
@danilvoe I did not fully understand what you are tying to explain.

We do have a `required` key to mark as not optional.

```
params: [
   {
       "key": "post['name']",
       "required": true,
       "type": "String",
       "notes": ["Name or title of the post"],
       "validations": ["should be less than or equal to 150 characters"]
   }
]
```

![image](https://user-images.githubusercontent.com/5062193/88208866-b6fb1600-cc06-11ea-8d4c-bf8bfe46d1c2.png)

**Comment by danilvoe** [comment]
@alameenkhader 

I'll try to explain it differently, the English language is bad.

Now you can describe the parameters that must be passed to execute the request.

But you cannot describe the entity model as a set of parameters that will be returned as a result of the query execution.

You can try to describe everything in the params section, but a person looking at a set of parameters will not be able to understand which of them are needed to complete the request, and which will come in the body of the response to the request.

**Comment by danilvoe** [comment]
The task that I want to solve is to convey to the API consumer - the limitations and opportunities that the response body will give. To do this, you need to somehow describe the data model (types of attributes and their description) that is returned in the response. In fact, we need another section of params, but for an answer.

**Comment by alameenkhader** [comment]
Got it.
